### PR TITLE
fix flatRateFulfillmentMethods query returns with wrong entities

### LINKED ISSUE #6237: flatRateFulfillmentMethods graphql query does not match the shipping schema
## Issue Description

Screenshot 2020-04-29 at 1 34 41 PM

## Possible Solution

change the schema of graphql ? or mongo ? 

### Versions

3.4.0

### PR DESCRIPTION
**Pull request by sheunglaili**
Resolves reactioncommerce/reaction#6237
Impact: minor
Type: bugfix

## Issue
flatRateFulfillmentMethods query returns with shipping entities instead of fulfillmentMethods
reactioncommerce/reaction#6237

## Solution
Querying shipping collection with aggregate to extract fulfillment methods , and paginate using api-utils

## Testing
Query through graphql explorer

### CODE REVIEW

File: src/queries/flatRateFulfillmentMethods.js [hunk 1]
```diff
@@ -15,7 +15,28 @@ export default async function flatRateFulfillmentMethods(context, input) {
...
-  return Shipping.find({
-    shopId
-  });
+  // aggregate pipeline to extract fulfillment methods inside shippment
+  return {
+    collection: Shipping,
+    pipeline: [
+      {
+        $match: {
+          shopId
```
Comment (aldeed) [inline src/queries/flatRateFulfillmentMethods.js:27]: Need to add addition match condition here:

```js
"provider.name": "flatRates"
```

Historically, there were other plugins storing their methods in the same collection.

File: src/queries/flatRateFulfillmentMethods.js [hunk 2]
```diff
@@ -15,7 +15,28 @@ export default async function flatRateFulfillmentMethods(context, input) {
...
+      },
+      {
+        $replaceRoot: {
+          newRoot: "$methods"
+        }
+      },
+      {
+        $set: {
+          "isEnabled": "$enabled"
+        }
```
Comment (aldeed) [inline src/queries/flatRateFulfillmentMethods.js:43]: Remove the `$set`. We handle all field name changes using GraphQL field resolvers. In `src/resolvers/FlatRateFulfillmentMethod/index.js`, you can add a line in the exported object:

```js
isEnabled: (node) => !!node.enabled
```

File: src/resolvers/Query/flatRateFulfillmentMethods.js [hunk 3]
```diff
@@ -22,13 +22,22 @@ export default async function flatRateFulfillmentMethods(_, args, context, info)
...
     includeHasPreviousPage: wasFieldRequested("pageInfo.hasPreviousPage", info),
     includeTotalCount: wasFieldRequested("totalCount", info)
   });
+
+  // getPaginatedResponsFromAggregate return null when no record return
+  // workaround by setting to 0 when total count is null
+  const preventZeroTotal = {
+    ...paginated,
+    totalCount: paginated.totalCount || 0
+  }
```
Comment (aldeed) [inline src/resolvers/Query/flatRateFulfillmentMethods.js]: The latest version of `api-utils` should fix this, so update that dependency and remove this workaround.

**Review by aldeed — CHANGES_REQUESTED** [review]
@sheunglaili Thank you for attempting a fix! There are a few issues here:

- For the top three lines of the PR description, you should edit them. After `Resolves #` put the issue ID for the GitHub issue that describes this problem. For the next two, delete all but one. (fix, minor)
- Every commit must have signoff or we cannot legally merge. Use `-s` with `git commit` command, or choose "Commit with signoff" if using a Git GUI.
- Other comments inline

**Comment by sheunglaili** [comment]
I have updated the requested changes ! Please review !

**Review by aldeed — CHANGES_REQUESTED** [review]
@sheunglaili Changes look good. A couple more things.

- The end of the path where you import `getPaginatedResponseFromAggregate` from needs to be `getPaginatedResponseFromAggregate.js`. Otherwise doesn't work.
- You need to run `npm install @reactioncommerce/api-utils@latest` and commit the file changes it makes. Otherwise this won't have the null/0 fix.

**Comment by sheunglaili** [comment]
> @sheunglaili Changes look good. A couple more things.
> 
>     * The end of the path where you import `getPaginatedResponseFromAggregate` from needs to be `getPaginatedResponseFromAggregate.js`. Otherwise doesn't work.
> 
>     * You need to run `npm install @reactioncommerce/api-utils@latest` and commit the file changes it makes. Otherwise this won't have the null/0 fix.

My bad for these. pushed new commit to fix it. thanks !

File: src/queries/flatRateFulfillmentMethods.js [hunk 4]
```diff
@@ -15,7 +15,24 @@ export default async function flatRateFulfillmentMethods(context, input) {
...
+      },
+      {
+        $unwind: "$methods"
+      },
+      {
+        $replaceRoot: {
+          newRoot: "$methods"
+        }
+      }
```
Comment (aldeed) [inline src/queries/flatRateFulfillmentMethods.js:44]: I discovered that there's an error when you request `shop` field because `shopId` is on the original root document. To fix it, please change this last `replaceRoot` stage to:

```js
{
        $replaceRoot: {
          newRoot: {
            $mergeObjects: [
              "$methods",
              {
                shopId: "$$ROOT.shopId"
              }
            ]
          }
        }
      }
```

**Review by aldeed — CHANGES_REQUESTED** [review]
@sheunglaili I tested this and it's mostly working but needs one change. Also, I noticed that the `flatRateFulfillmentMethod` query (find one) has the same problem. Can you fix it in the `flatRateFulfillmentMethod.js` file, too?

Change this:

```js
  return Shipping.findOne({
    _id: methodId,
    shopId
  });
```

To this:

```js
  const doc = await Shipping.findOne({
    "methods._id": methodId,
    shopId
  });
  if (!doc) return null;

  const method = doc.methods.find((method) => method._id === methodId);
  return {
    ...method,
    shopId
  };
```

That should be all you need to do to fix.

**Comment by sheunglaili** [comment]
please review again thanks

**Review by aldeed — APPROVED** [review]
